CREATE TABLE PostsDB (
    id INTEGER AUTO_INCREMENT NOT NULL,
    title VARCHAR(20) NOT NULL,
    content VARCHAR (510) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Users (
    id INTEGER AUTO_INCREMENT NOT NULL,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);